version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - richo225
  assignees:
  - richo225
  ignore:
  - dependency-name: graphql
    versions:
    - 1.12.0
    - 1.12.3
    - 1.12.4
    - 1.12.5
    - 1.12.6
    - 1.12.7
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.12.0
    - 3.12.1
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
  - dependency-name: database_cleaner
    versions:
    - 1.8.5
    - 2.0.0
