version: '3.4'
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  gem_cache:
  db_data:
  # redis data doesn't need to persist right now