version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - ./bundle-path:/bundle
    environment:
      BUNDLE_PATH: /bundle/vendor
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.dist
volumes:
  bundle-path:
  # redis data doesn't need to persist right now