name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Add an issue reference
      uses: kentaro-m/add-an-issue-reference-action@v1.0.0
    
    


